### ISSUE TITLE
Parsing date/time values

### ISSUE THREAD

**Issue by tkopecek** [cvt-oss/fb-invoice-pdf-analyzer#5]
Similar to #4 - datetime values could be already in ISO format.

**Comment by agiertli** [comment]
Hi @tkopecek ,

see:
https://github.com/cvt-oss/fb-invoice-pdf-analyzer/commit/c69f78114c387df8bcf330c27402f6f4a11ac242

Instead of String, I am now using LocalDateTime - which natively supports ISO format (without Timezone).

Date is now returned like this:

`"paidOn": "2019-01-19T15:56:00"`

Let me know if this can be closed or if you'd like any further improvements (like differently formatted response or including timezone..)

**Comment by tkopecek** [comment]
Works, thanks!
